### ISSUE TITLE
DR tracker seems busted

### ISSUE THREAD

**Issue by SamiRayR** [ManneN1/GladiusEx-WotLK#13] opened 2024-03-12 20:21 UTC
Since the recent updates, some DRs fail to track, I notice this especially on blind/fear and kidney shot/controlled stun. The icon appears, but no counter number, and the icon persists after it has expired.

**Comment by ManneN1** [comment] 2024-03-12 20:35
Ill have a look at it tomorrow. Thanks for reporting.

**Comment by ManneN1** [comment] 2024-03-17 10:12
I've taken a look at it and I am not able to reproduce. I have found another issue with the updated DRTracker, but it does not seem to be related.

Please share more details on how to reproduce. Are you using the new "Show on Apply" option or not? What exact order of spells (and timing) causes the issue?

Possibly, a replay match ID could be shared, if you have that available (but please still tell me where in the match the issue is supposed to appear).

**Comment by SamiRayR** [comment] 2024-03-19 16:11
I reverted to a previous version for playability. I'll redownload and see if I can reproduce

**Comment by ManneN1** [comment] 2024-04-01 13:44
Tried with some updates now. Let's see if that works better. Closing for now (feel free to re-open or add new comments).

**Closed as completed by ManneN1** 2024-04-01 13:44 UTC

**Comment by SamiRayR** [comment] 2024-04-04 18:07
I didn't get around to reinstalling the broken version and getting a replay ID, mainly because it looks like the newest version fixed whatever was broken in the first place. Thanks again
