### ISSUE TITLE
CD and aura module problems

### ISSUE THREAD

**Issue by SamiRayR** [ManneN1/GladiusEx-WotLK#7] opened 2023-10-25 00:51 UTC
Hi ManneN1, sorry for the long delay.

Even after recent edits, the CD module seems to be broken still, and the aura module might still have issues too.

The presence and length of cooldowns seems more or less good now, at least in the checkbox selection options, but it has trouble handling them somehow. The behavior I am seeing, for example, is if I tell the testing pane that arena2 is an MM hunter, who should show icon for scatter shot, scatter doesn't show up for test frames, or for actual arena/party units. Other abilities do (e.g. feign death) but scatter and some others are somehow missing, other classes have the same issue with some abilities too- they are selectable as options, but don't end up being shown. Even when 'hide until spec detected' is unchecked, they are still not shown, so it doesn't seem like the issue is there or, at least, not directly. 

About auras, I ordinarily use SBF to show enemy/party buffs and debuffs, but it has an ugly cobbled together look and preferred to have it integrated in the party/arena frames, but when I tried Gladiusex's, even after setup (adding whitelist filter) the display didn't match in strange ways. For example, when my warrior partner charged someone, charge appeared as an aura on them for a long time, with a tooltip like the one a warrior would see on their bar. Maybe it was generating cooldowns of the caster instead of the aura effects on the unit? Not sure, I will try to repeat that behavior later and explain it better. 

I have a list of cooldowns that I can still upload but that part seems solved for now. Is there any other way I can help you?

**Comment by ManneN1** [comment] 2023-10-25 15:25
Testing:
![image](https://github.com/ManneN1/GladiusEx-WotLK/assets/16864855/376345eb-3296-4bb8-a2b1-ea8c432060c5)

In arena:
![image](https://github.com/ManneN1/GladiusEx-WotLK/assets/16864855/1c0becdc-8eb4-4496-b0ed-7fcc7c05ea85)

Second to last cooldown is Scatter Shot, and it seems to work just fine for me. Also works fine in actual arena, triggering the CD as expected, and showing normally once available again. Are you experiencing this for friendly or enemy units primarily?

W.r.t. Auras, please make a separate issue report with clear guidance on what the issue is and how to reproduce it. Pictures are usually good.

Note: Unless you provide clear instructions on how to reproduce I will be closing this shortly since I am not able to reproduce the issue.

**Comment by ManneN1** [comment] 2023-10-25 16:22
> The presence and length of cooldowns seems more or less good now

> I have a list of cooldowns that I can still upload

If you have any examples of particular cooldowns behaving incorrectly (e.g,, missing entirely, not being spec specific, not being baseline, incorrect cd or other similar issues) feel free to create separate issues for this, or create a pull request. It is much appreciated, as I personally do not use the cooldown module much myself (beyond trinkets).

Note: Just a tip, having the correct spell IDs makes things much, much easier for me to work with (instead of me having to look it up).

**Comment by SamiRayR** [comment] 2023-10-26 14:48
I just tried again, clean install, deleted also the settings file in the
account's SavedVariables folder to make sure it wasn't being fouled by
previous settings. For me, it is still not working in the way described. My arena partner has the same issue
with Gladiusex too. For us, and others I have talked to on Warmane, the CD
module has these issues. In the screenshots you posted, it does not... How
is this possible? Could we be missing some library? Does the code-> zip download method leave something out? (It has for some other's like BannZay's PlatesClasses that require downloading from the release page)

**Comment by SamiRayR** [comment] 2023-10-26 14:54
Here is an example clip where Bestial Wrath and Intimidation fail to show
up:

https://github.com/ManneN1/GladiusEx-WotLK/assets/96414645/6e78d138-8d8b-4d97-bb7f-eca2b85830b4

**Comment by SamiRayR** [comment] 2023-10-26 16:19
Update: 

I tried disabling all addons and enabling only GladiusEx. It now works, at least in testing mode. I do not know how to explain this, conflicting libraries from some other very common, potentially essential addon? I will try enabling things 1 by 1 to isolate.

**Comment by ManneN1** [comment] 2023-10-26 17:48
> Here is an example clip where Bestial Wrath and Intimidation fail to show up: https://github.com/ManneN1/GladiusEx-WotLK/assets/96414645/6e78d138-8d8b-4d97-bb7f-eca2b85830b4

So for this one, it looks like you have "Hide talents until detected" active, causing the cooldowns to not show up ever (since it's only a test unit it will never "find" that it has been used).

**Comment by SamiRayR** [comment] 2023-10-27 04:21
As I mentioned in the first post, that problem occurs regardless of that option being checked. Here is an in-arena example from party:

https://github.com/ManneN1/GladiusEx-WotLK/assets/96414645/79fdd474-e880-4ad8-a9c3-6bd3fedf4b98 - maybe that is because it failed to detect spec before game started, but this seems to occur after the game starts. I will try to provide proof later.

Another problem in this update seems to be that Every Man For Himself no longer shows as the PVP trinket cooldown, it did in the copy of Gladiusex that I used before this month. If you can't duplicate this, there must be some library conflict or missing libraries, or something...

As far as missing cooldowns:

Hunter pet
Intervene:
53476 [spellid]
30s cooldown for surv/mm
21s for bm (but bm doesnt take intervening pet, afaik, so maybe program to only apply to mm/surv, and leave icon off for bm)

Hunter
Roar of Sacrifice:
53480
60s
[ditto]

Priest (Shadow)
Psychic Horror
64044
120s

Warrior
Shield Bash
72
12s 
[also shares cooldown with pummel; if shield bash is used, pummel goes on 12s cooldown, if pummel is used, shield bash goes on 10s cd]

Hunter traps are CD linked by school, it currently links freezing trap and arrow, but does not link frost trap

Also, Balance druid's starfall cooldown is 60s (90s cd, glyphed to 60s)

Ele shaman's Thunderstorm is glyphed to 35s rather than 45s

Hammer of Justice can be reduced to 40s not 45s by early prot talents taken by ret and preg specs, deep prot gets a further 10s reduction, not sure how to do that 1.

mana tide and nature's swiftness were under 'talents' rather than the resto spec for shamans

it assigns hysteria to unholy spec, but this is blood spec

it assigns cold blood to sub, but this is assass spec

fade is technically a default spell, but only shadow can use it to get out of snares (the only pvp use), so best tracked as a shadow spec spell

Inner focus is tracked as a disc talent, but it is high enough in the disc tree that it's fairly default for shadow spec as well


I took the liberty of editing the LUA files, I believe I did so correctly, you can check:
[LibCooldownTracker-1.0 changes.zip](https://github.com/ManneN1/GladiusEx-WotLK/files/13184907/LibCooldownTracker-1.0.changes.zip)


I did not fix cold blood or hysteria yet


Also, in the DR module, Cyclone is missing. And for the DR icons, Blind is missing from the Fear category

**Comment by ManneN1** [comment] 2023-10-27 16:50
> As I mentioned in the first post, that problem occurs regardless of that option being checked. Here is an in-arena example from party:
> https://github.com/ManneN1/GladiusEx-WotLK/assets/96414645/79fdd474-e880-4ad8-a9c3-6bd3fedf4b98 - maybe that is because it failed to detect spec before game started, but this seems to occur after the game starts. I will try to provide proof later.

I have fixed/improved friendly unit spec detection, and also fixed an issue which caused the cooldowns module to not update after a spec had been detected in https://github.com/ManneN1/GladiusEx-WotLK/commit/4a7923d132d971a649a03d4b2232b846025e9aea.

> Another problem in this update seems to be that Every Man For Himself no longer shows as the PVP trinket cooldown, it did in the copy of Gladiusex that I used before this month. If you can't duplicate this, there must be some library conflict or missing libraries, or something..

I have updated the libraries to use the same (updated) ones as in the backported version of WeakAuras in https://github.com/ManneN1/GladiusEx-WotLK/commit/f1445af7f3a2cb7db6118e80d1967e2c7618d43f.

However, can you clarify what the issue w.r.t. the trinkets is? EMFH shows as EMFH and not as the PvP trinket icon? Please make a **new issue** for this.

> Hunter pet Intervene: 53476 [spellid] 30s cooldown for surv/mm 21s for bm (but bm doesnt take intervening pet, afaik, so maybe program to only apply to mm/surv, and leave icon off for bm)
> Hunter Roar of Sacrifice: 53480 60s [ditto]
> Priest (Shadow) Psychic Horror 64044 120s
> Warrior Shield Bash 72 12s [also shares cooldown with pummel; if shield bash is used, pummel goes on 12s cooldown, if pummel is used, shield bash goes on 10s cd]
> Hunter traps are CD linked by school, it currently links freezing trap and arrow, but does not link frost trap
> Also, Balance druid's starfall cooldown is 60s (90s cd, glyphed to 60s)
> Ele shaman's Thunderstorm is glyphed to 35s rather than 45s
> Hammer of Justice can be reduced to 40s not 45s by early prot talents taken by ret and preg specs, deep prot gets a further 10s reduction, not sure how to do that 1.
> mana tide and nature's swiftness were under 'talents' rather than the resto spec for shamans
> it assigns hysteria to unholy spec, but this is blood spec
> it assigns cold blood to sub, but this is assass spec
> fade is technically a default spell, but only shadow can use it to get out of snares (the only pvp use), so best tracked as a shadow spec spell
> Inner focus is tracked as a disc talent, but it is high enough in the disc tree that it's fairly default for shadow spec as well

Fixed all of these in https://github.com/ManneN1/GladiusEx-WotLK/commit/fc9f81b31f8982d82c29a2bb0259bcd60cc0693b. Thanks for your updated file, I used it as a base.

> Also, in the DR module, Cyclone is missing.

Fixed in https://github.com/ManneN1/GladiusEx-WotLK/commit/ac5c624da5baa2647f38f5934cbba552ed83d9de. In order to prevent showing the option to modify the icon for categories with only one spell id (which makes no sense to do) I had a check in place to not add such categories to the category icon selection page, however the check was placed incorrectly and also removed the option to even toggle it on / off.

> And for the DR icons, Blind is missing from the Fear category

The same icon can only show up once in the dropdown (as to avoid a billion duplicate Polymorph icons for each rank spell id etc). Seduction and Blind share the same icon, thus if you want to get the Blind icon, use the Seduction icon.

**Closed as completed by ManneN1** 2023-10-27 16:50 UTC

**Comment by ManneN1** [comment] 2023-10-27 17:18
> > And for the DR icons, Blind is missing from the Fear category
> 
> The same icon can only show up once in the dropdown (as to avoid a billion duplicate Polymorph icons for each rank spell id etc). Seduction and Blind share the same icon, thus if you want to get the Blind icon, use the Seduction icon.

I have made an update in https://github.com/ManneN1/GladiusEx-WotLK/commit/ebb65b55542d8cfba38fa7a13bb55f942fc488ba which is hopefully more in line with what users are expecting.

**Comment by SamiRayR** [comment] 2023-10-28 06:34
Thank you for your work on this wonderful addon
