### ISSUE TITLE
Problems with Soundalerter Enhanced

### ISSUE THREAD

**Issue by wowluanoob** [ManneN1/GladiusEx-WotLK#15] opened 2024-07-06 11:52 UTC
Hello SoundAlerter Enhanced from Cortes Jeremy doesnt work correctly with GladiusEx. When i join a battleground soundalerter stops working. I get no errors whatsoever. I noticed the combat log stops updating. In order to make it work i have to disable sound alerter and reenable it. Is that some kind of library issue? Is it possible to be fixed somehow?
EDIT: CombatLogClearEntries() fixes it for some reason.
EDIT2: I suspect the else part of this code is responsible for this. Because it stops logging for battlegrounds https://github.com/ManneN1/GladiusEx-WotLK/blob/842f88f6df642a589cf14b5558d293e416112cbd/GladiusEx.lua#L698-L737

**Comment by ManneN1** [comment] 2024-07-06 13:54
I find it unlikely that this part of the code would cause that issue.

It could be a library issue, it's perfectly fine to replace all the libraries except AceTimer with the ones in SoundAlerter.

Does the issue happen also with GladiusEx disabled? If so, I find it more likely that the combat log is just breaking. Which it does regularly in WotLK. In order to fix it breaking you need this AddOn (or similar) - which does indeed utilize CombatLogClearEntries(): https://www.wowinterface.com/downloads/info16001-CombatLogFix.html


Let me know if either of the potential solutions worked.

**Comment by wowluanoob** [comment] 2024-07-06 14:04
It doesnt happen without gladiusex since it started happening after i installed it. But I found the issue if i enable spectate feature combat log breaks and stops updating (displaying anything new). combatlogclearentries() reenables the combat log thus fixing the problem. idk where how and why the combat log is stopped after enabling spectate feature.

**Comment by wowluanoob** [comment] 2024-07-06 14:10
From reading code both addons use COMBAT_LOG_EVENT_UNFILETERED and from searching for it in gladiusex i find that only libaurainfo and spectate use UnregisterEvent:COMBAT_LOG_EVENT_UNFILETERED so that may be the culprit. Or something with the callbacks there or idk

**Comment by wowluanoob** [comment] 2024-07-06 14:19
Spectate -> use server data makes soundalerter not working ( on warmane )

**Comment by ManneN1** [comment] 2024-07-06 17:15
Not able to reproduce. SoundAlerter + GladiusEx (with and without "Use Server Data") works just fine for me in both World and BGs on e.g., Warmane.

**Comment by wowluanoob** [comment] 2024-07-06 18:10
will check again. it might be because i got a bunch of skada and elvui errors on first time launch of gladiusex and i disabled skada but didnt relaunch wow maybe some error stuck... after relaunching and disabling server data it works normally

**Comment by ManneN1** [comment] 2024-07-06 18:21
Okay, then I'll be closing the issue. Feel free to comment if the issue comes back (and seems to be related to GladiusEx).

**Closed as completed by ManneN1** 2024-07-06 18:21 UTC
